version: "3.7"

services:
  apache:
    container_name: webs-apache
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-apache-dev
    environment:
      - FORCE_REINSTALL=${FORCE_REINSTALL:-false}
    ports:
      - "80:80"
    volumes:
      # Empty mounts for apache & runtime files
      - /var/www/webs/node_modules
      - /var/www/webs/temp
      - /var/www/webs/vendor
      # Webs files
      - .:/var/www/webs
      # Apache & PHP config
      - .docker/config/httpd-vhosts.conf:/etc/apache2/conf-enabled/vhosts.conf:ro
      - .docker/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  db:
    container_name: webs-mariadb
    image: mariadb:10.8
    ports:
      - 3316:3306
    environment:
      - MARIADB_ROOT_PASSWORD=password

  adminer:
    image: adminer
    container_name: webs-adminer
    restart: always
    ports:
      - 5050:8080
