name: tests

on: [push, pull_request]

jobs:
  latte:
    name: Latte with PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: ["8.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/setup
        with:
          php-version: ${{ matrix.php }}

      - run: composer run-script latteLint
        name: Test

  build:
    name: build assets (npm ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/setup
        with:
          node: true
          node-version: ${{ matrix.node-version }}
          python: true

      - run: npm run build
        env:
          CI: true

  nette:
    name: PHP (Nette Tester) ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["8.1", "8.2", "8.3"]
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: recursive
      - uses: ./.github/setup
        with:
          php-version: ${{ matrix.php }}
          node: true
      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -r tests/api/requirements.txt
        name: Pip install

      - run: composer run-script test
        name: Test
      - if: failure()
        name: Failure output
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: tests/**/*.actual

  php-stan:
    name: PHPStan ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: ["8.1"]
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: recursive
      - uses: ./.github/setup
        with:
          php-version: ${{ matrix.php }}
      - uses: php-actions/phpstan@v3
        with:
          level: 5
          path: app/ tests/
